// Icônes centralisées — 1 seul fichier à importer dans tout le projet
// Au lieu de `import { Menu } from "lucide-react"` partout, faire `import { Menu } from "@/lib/icons"`
export {
  Menu,
  MoreVertical,
  Wifi,
  RotateCw,
  Plus,
  ArrowUp,
  AudioLines,
  FileText,
  X,
  Image as ImageIcon,
  Globe,
  Sliders,
  Check,
  ChevronDown,
  ChevronRight,
  Search,
  SquarePen,
  Star,
  Trash2,
  Settings,
  Shield,
  User,
  ArrowRight,
  Mic,
  Volume2,
  MousePointerClick,
  Copy,
  ThumbsUp,
  ThumbsDown,
  Loader2,
  CornerDownLeft,
  Lightbulb,
  Eye,
  ArrowDown,
} from "lucide-react";
